function Scanner()
    figHandle = figure('Position', [300, 800, 600, 850]);
    %add main panel
    mainPanel = uipanel('Title', '', 'Position', [0.01,0.4, 0.98, 0.59],...
                        'BackgroundColor', 'green');
    
    controlPanel = uipanel('Title','', 'Position',[0.01,0.01,0.98, 0.4],...
                        'BackgroundColor', 'red');
                        
    cameraCapturePanel = uipanel('Parent', controlPanel, 'Title', 'Camera capture',...
                        'Position', [0.01, 0.01, 0.48, 0.48],...
                        'BackgroundColor','white');
                        
    processPanel = uipanel('Parent', controlPanel, 'Title', 'Process',...
                        'Position', [0.01, 0.51, 0.48, 0.48],...
                        'BackgroundColor','white');
                        
    cameraTweakPanel = uipanel('Parent', controlPanel, 'Title', 'Camera Tweak',...
                        'Position', [0.5, 0.51, 0.49, 0.48],...
                        'BackgroundColor','white'); 
    
    calibParameterPanel = uipanel('Parent', controlPanel, 'Title', 'Calib parameter',...
                        'Position', [0.5, 0.01, 0.49, 0.48],...
                        'BackgroundColor','white'); 
                        
    %//*****************Create menu*******************
    
    % menu load data
    mnLoadData  = uimenu(figHandle, 'Label', 'Data');
    mnLoadImage = uimenu('Parent', mnLoadData, 'Label', 'Load Images'); %choose the folder for graycode and phaseshift
    mnImportPC  = uimenu('Parent', mnLoadData, 'Label', 'Import Poincloud');
    mnExportPC  = uimenu('Parent', mnLoadData, 'Label', 'Export Pointcloud');
    mnExit      = uimenu('Parent', mnLoadData, 'Label', 'Exit');
    
    % Menu load and calib camera and projector
    mnCalib     = uimenu(figHandle, 'Label', 'Calib system');
    mnNewCalib  = uimenu(mnCalib, 'Label', 'New Calib');
    mnLoadCalib = uimenu(mnCalib, 'Label', 'Load calib');
    mnSaveCalib = uimenu(mnCalib, 'Label', 'Save Result');
    
    %//**********************************************\\
    
    % create two button in process panel
    %show point cloud button
    btShowPC = uicontrol('Parent', processPanel,...
                        'string', 'Show Point Cloud', 'Position', [60 85 160 40],...
                        'callback',@hello);
                        
    % Reconstruct button
    btReconstruct = uicontrol('Parent', processPanel,...
                        'string', 'Reconstruct', 'Position', [60 25 160 40],...
                        'callback',@hello);                   
    
     %//*****************CAMERA TWEAK*******************
    %Create slider in camera tweak
    %static text constrast
    uicontrol(cameraTweakPanel,'style', 'text', 'string', 'Constrast',...
              'Position', [5, 100, 100, 20], 'fontsize', 9,...
              'BackgroundColor','white','horizontalalignment','right');
              
    %%%%% Make slider constrast
    slConstrast = uicontrol(cameraTweakPanel, 'style', 'slider', ...
                        'Position', [130, 100, 140, 20], 'Enable', 'on',...
                        'Value', 50, 'min', 0, 'max', 100);
                %******************                    
    %static text white balance              
    uicontrol(cameraTweakPanel,'style', 'text', 'string', 'White Balance',...
              'Position', [5, 60, 100, 20], 'fontsize', 9,...
              'BackgroundColor','white','horizontalalignment','right');
              
    %%%%% Make slider white balance              
    slWhiteBalance = uicontrol(cameraTweakPanel, 'style', 'slider', ...
                        'Position', [130, 60, 140, 20], 'Enable', 'on',...
                        'Value', 50, 'min', 0, 'max', 100);          
                %****************** 
    %static text Exposure  
    uicontrol(cameraTweakPanel,'style', 'text', 'string', 'Exposure',...
              'Position', [5, 20, 100, 20], 'fontsize', 9,...
              'BackgroundColor','white','horizontalalignment','right');
    
    %Make slider Exposure    
    slExposure = uicontrol(cameraTweakPanel, 'style', 'slider', ...
                        'Position', [130, 20, 140, 20], 'Enable', 'on',...
                        'Value', 50, 'min', 0, 'max', 100);
    %***************************************************
    
    %%*************************CALIBRATION PARAMETER*******************
    
    %Static text
    % Square Width
    uicontrol(calibParameterPanel,'style', 'text', 'string', 'Square Width:',...
              'Position', [5, 120, 100, 20], 'fontsize', 9,...
              'BackgroundColor','white','horizontalalignment','right');
              
    txtSquareWidth = uicontrol(calibParameterPanel, 'style', 'edit', ....
              'Position', [180, 120, 50, 20], 'fontsize', 9, ...
              'string', '15');
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%     
    % Square Height               
    uicontrol(calibParameterPanel,'style', 'text', 'string', 'Square Height:',...
              'Position', [5, 95, 100, 20], 'fontsize', 9, ...
              'BackgroundColor','white','horizontalalignment','right');
              
    txtSquareHeight = uicontrol(calibParameterPanel, 'style', 'edit', ....
              'Position', [180, 95, 50, 20], 'fontsize', 9, ...
              'string', '15');
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%     
    % Horizontal Squares               
    uicontrol(calibParameterPanel,'style', 'text', 'string', 'Hor Squares:',...
              'Position', [5, 70, 100, 20], 'fontsize', 9, ...
              'BackgroundColor','white','horizontalalignment','right');
              
    txtHorSquare = uicontrol(calibParameterPanel, 'style', 'edit', ....
              'Position', [180, 70, 50, 20], 'fontsize', 9, ...
              'string', '0');              
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Veritcal Squares                    
    uicontrol(calibParameterPanel,'style', 'text', 'string', 'Ver Squares:',...
              'Position', [5, 45, 100, 20], 'fontsize', 9, ...
              'BackgroundColor','white','horizontalalignment','right');
    
    txtVerSquare = uicontrol(calibParameterPanel, 'style', 'edit', ....
              'Position', [180, 45, 50, 20], 'fontsize', 9, ...
              'string', '0');
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Thresh hold                
    uicontrol(calibParameterPanel,'style', 'text', 'string', 'Thresh hold:',...
              'Position', [5, 20, 100, 20], 'fontsize', 9,
              'BackgroundColor','white','horizontalalignment','right');
    
    txtThreshHold = uicontrol(calibParameterPanel, 'style', 'edit', ....
              'Position', [180, 20, 50, 20], 'fontsize', 9, ...
              'string', '100');
    %******************************************************************
    
    %------------------ CAMERA CAPTURE -----------------------
    uicontrol(cameraCapturePanel,'style', 'text', 'string', 'Thresh hold:',...
              'Position', [5, 110, 100, 20], 'fontsize', 9,
              'BackgroundColor','white','horizontalalignment','right');
    
    txtCameraCapture = uicontrol(cameraCapturePanel, 'style', 'edit', ....
                  'Position', [180, 110, 50, 20], 'fontsize', 9, ...
                  'string', '100');  
                
    %show point cloud button
    btShowPC = uicontrol('Parent', cameraCapturePanel,...
                        'string', 'Collect Data', 'Position', [60 45 160 40],...
                        'callback',@hello);          
      
    %---------------------------------------------------------
endfunction

function hello()
    disp('Hello world');
endfunction

%h = figure;
%hp = uipanel('Title','Main Panel','FontSize',12,...
%             'BackgroundColor','white',...
%             'Position',[.25 .1 .67 .67]);
%hsp = uipanel('Parent',hp,'Title','Subpanel','FontSize',12,...
%              'Position',[.4 .1 .5 .5]);
%hbsp = uicontrol('Parent',hsp,'String','Push here',...
%              'Position',[18 18 72 36]);

